version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=secret 
      - POSTGRES_DB=banking 
    
  api: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/banking?sslmode=disable 
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
    
